---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-SGF-Go-Rotator
no_index:
  directory:
    - t
    - inc
requires:
  Games::SGF::Go: 0.993
  Games::SGF::Util: 0.993
resources:
  bugtracker: https://github.com/DrHyde/perl-modules-Games-SGF-Go-Rotator/issues
  repository: https://github.com/DrHyde/perl-modules-Games-SGF-Go-Rotator
version: 1.21
